apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rstudio
  name: rstudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rstudio
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - image: jupyter/r-notebook:acb539921413
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 200
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        name: rstudio
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 500Mi
        volumeMounts:
        - mountPath: /home/jovyan
          name: rstudio-data
        - mountPath: /mnt
          name: rstudio-library
      volumes:
      - name: rstudio-data
        emptyDir: {}
        # persistentVolumeClaim:
        #  claimName: rstudio-data
      - name: rstudio-library
        emptyDir: {}
        # persistentVolumeClaim:
        #  claimName: rstudio-library

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rstudio
  name: rstudio-http
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: rstudio
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
  labels:
    app: rstudio
  name: rstudio
spec:
  rules:
  - host: rstudio.doxpert.co.kr
    http:
      paths:
      - backend:
          serviceName: rstudio-http
          servicePort: http
        path: /
